name: my_shop
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  shimmer: ^2.0.0
  im_stepper: ^1.0.1+1
  carousel_slider: ^4.1.1
  flutter_image_slideshow: ^0.1.4
  lottie: ^1.4.2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  infinite_scroll_pagination: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
    
    
  

flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/
